version: "3.8"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env

volumes:
  postgres-data: